### ISSUE TITLE
Optimize

### ISSUE THREAD

**Issue by SgnJp** [SgnJp/mload#4]

**Comment by SgnJp** [comment]
Now we can start optimizing our solution using test.h:
yury@Yury-home:~/Dropbox/uni/mload/git/mload/ex3$ time timeout 120s ./test.sh 
(1/8) TEST PASSED!: problems/random_ksat1.dimacs
(2/8) TEST PASSED!: problems/random_ksat3.dimacs
(3/8) TEST PASSED!: problems/subsetsum_random.dimacs
(4/8) TEST FAILED!: problems/test.dimacs
(5/8) TEST PASSED!: problems/random_ksat2.dimacs
(6/8) TEST PASSED!: problems/simple.dimacs
(7/8) TEST PASSED!: problems/factoring2.dimacs

real	2m0.003s
user	0m2.957s
sys	0m0.088s

Now our solution run out of timeout of 120s, previous solution cnf_solver.py take 4-8s in average.
Minisat solves all problems in 0.04s

**Comment by erniejunior** [comment]
This is truly beautiful!
